export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT = 'LOGOUT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const DELETE_TOKEN = 'DELETE_TOKEN'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SIGNUP_CANCELLED = 'SIGNUP_CANCELLED'

export const SET_ERROR = 'SET_ERROR'
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export default {
  LOGIN_REQUEST,
  LOGOUT,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGIN_CANCELLED,
  SAVE_TOKEN,
  DELETE_TOKEN,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  SIGNUP_CANCELLED,
  CLEAR_ERROR,
  ERROR,
  SET_ERROR,
}
